name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
 
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu_latest 
        install: |
            sudo apt-get update
            sudo apt install golang-go 

           
        run: |  
            export PATH=$PATH:/usr/local/go/bin
            rm go$GOLANG_VERSION.src.tar.gz
            go version

            


     


 
  

