name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
 
  build-and-test:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu_latest 
        run: go test -v ./...


 
  

