name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
 
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: alpine_latest 
        install: |
              wget https://golang.org/dl/go1.20.1.linux-arm64.tar.gz
              tar -C /usr/local -xzf go1.20.1.linux-arm64.tar.gz        
        run: |  
            export PATH=$PATH:/usr/local/go/bin
            rm go$GOLANG_VERSION.src.tar.gz
            go version

            


     


 
  

